import { Archive, Inbox, Send, Trash2 } from "lucide-react";

// export seed mails
// export const mails = [
//   {
//     id: "507f1f77bcf86cd799439001",
//     sender: {
//       id: "507f1f77bcf86cd799439011",
//       name: "William Smith",
//       email: "williamsmith@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Meeting Tomorrow",
//     text: "Hi, let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and have some ideas I'd like to share. It's crucial that we align on our next steps to ensure the project's success.\n\nPlease come prepared with any questions or insights you may have. Looking forward to our meeting!\n\nBest regards, William",
//     date: new Date("2024-11-30T14:30:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["meeting", "work", "important"],
//   },
//   {
//     id: "507f1f77bcf86cd799439002",
//     sender: {
//       id: "507f1f77bcf86cd799439012",
//       name: "Sarah Johnson",
//       email: "sarah.j@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Project Update Report",
//     text: "Hello Mitul,\nI've attached the latest project update report for your review. Please let me know if you need any clarification.\n\nRegards,\nSarah",
//     date: new Date("2024-11-29T14:30:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["work", "report"],
//   },
//   {
//     id: "507f1f77bcf86cd799439003",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439013",
//       name: "John Doe",
//       email: "john.doe@example.com",
//     },
//     subject: "Re: Client Presentation",
//     text: "Hi John,\nI've reviewed the presentation and made some adjustments. Let's discuss these changes tomorrow.\n\nBest,\nMitul",
//     date: new Date("2024-11-09T16:45:00.000Z").toISOString(),
//      read: true,
//     archived: true,
//     trashed: false,
//     labels: ["client", "presentation"],
//   },
//   {
//     id: "507f1f77bcf86cd799439004",
//     sender: {
//       id: "507f1f77bcf86cd799439014",
//       name: "Emma Wilson",
//       email: "emma.w@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Team Building Event",
//     text: "Dear Mitul,\nWe're planning a team building event next month. Please fill out the preference form attached.\n\nThanks,\nEmma",
//     date: new Date("2024-10-19T11:20:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["team", "event"],
//   },
//   {
//     id: "507f1f77bcf86cd799439005",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439015",
//       name: "David Brown",
//       email: "david.b@example.com",
//     },
//     subject: "Budget Review",
//     text: "David,\nCan we schedule a meeting to review the Q4 budget?\n\nRegards,\nMitul",
//     date: new Date("2024-10-18T13:15:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: true,
//     labels: ["finance", "important"],
//   },
//   {
//     id: "507f1f77bcf86cd799439006",
//     sender: {
//       id: "507f1f77bcf86cd799439012",
//       name: "Sarah Johnson",
//       email: "sarah.j@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Project Timeline Update",
//     text: "Hi Mitul,\nI've updated the project timeline based on our recent discussion. Please review when you have a moment.\n\nBest regards,\nSarah",
//     date: new Date("2024-10-17T09:30:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["project", "urgent"],
//   },
//   {
//     id: "507f1f77bcf86cd799439007",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439016",
//       name: "Michael Chen",
//       email: "m.chen@example.com",
//     },
//     subject: "API Documentation Review",
//     text: "Michael,\nCould you please review the updated API documentation I've prepared?\n\nThanks,\nMitul",
//     date: new Date("2024-10-16T14:25:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["technical", "documentation"],
//   },
//   {
//     id: "507f1f77bcf86cd799439008",
//     sender: {
//       id: "507f1f77bcf86cd799439017",
//       name: "Lisa Anderson",
//       email: "l.anderson@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Weekly Status Report",
//     text: "Dear Mitul,\nPlease find attached the weekly status report for your review.\n\nRegards,\nLisa",
//     date: new Date("2024-10-15T16:00:00.000Z").toISOString(),
//      read: true,
//     archived: true,
//     trashed: false,
//     labels: ["report", "weekly"],
//   },
//   {
//     id: "507f1f77bcf86cd799439009",
//     sender: {
//       id: "507f1f77bcf86cd799439018",
//       name: "Robert Taylor",
//       email: "r.taylor@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Client Meeting Notes",
//     text: "Mitul,\nHere are the notes from today's client meeting. Please let me know if I missed anything.\n\nBest,\nRobert",
//     date: new Date("2024-10-14T11:45:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["client", "meeting"],
//   },
//   {
//     id: "507f1f77bcf86cd799439010",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439019",
//       name: "Jennifer Lee",
//       email: "j.lee@example.com",
//     },
//     subject: "Design Review Meeting",
//     text: "Hi Jennifer,\nLet's schedule a design review meeting for the new feature.\n\nBest,\nMitul",
//     date: new Date("2024-10-13T15:30:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["design", "meeting"],
//   },
//   {
//     id: "507f1f77bcf86cd799439021",
//     sender: {
//       id: "507f1f77bcf86cd799439022",
//       name: "Alex Martinez",
//       email: "a.martinez@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Resource Allocation",
//     text: "Dear Mitul,\nCan we discuss the resource allocation for the upcoming sprint?\n\nThanks,\nAlex",
//     date: new Date("2024-10-12T10:20:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["planning", "resources"],
//   },
//   {
//     id: "507f1f77bcf86cd799439023",
//     sender: {
//       id: "507f1f77bcf86cd799439024",
//       name: "Rachel Green",
//       email: "r.green@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Marketing Campaign Update",
//     text: "Hi Mitul,\nHere's the latest update on our marketing campaign performance.\n\nBest regards,\nRachel",
//     date: new Date("2024-10-11T13:15:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["marketing", "report"],
//   },
//   {
//     id: "507f1f77bcf86cd799439025",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439026",
//       name: "Chris Wilson",
//       email: "c.wilson@example.com",
//     },
//     subject: "Code Review Request",
//     text: "Chris,\nCould you please review the latest code changes I pushed to the repository?\n\nThanks,\nMitul",
//     date: new Date("2024-10-10T09:45:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["technical", "review"],
//   },
//   {
//     id: "507f1f77bcf86cd799439027",
//     sender: {
//       id: "507f1f77bcf86cd799439028",
//       name: "Sophie Turner",
//       email: "s.turner@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Holiday Schedule",
//     text: "Dear Mitul,\nPlease review and confirm the upcoming holiday schedule for the team.\n\nBest,\nSophie",
//     date: new Date("2024-10-09T14:30:00.000Z").toISOString(),
//      read: true,
//     archived: true,
//     trashed: false,
//     labels: ["hr", "schedule"],
//   },
//   {
//     id: "507f1f77bcf86cd799439029",
//     sender: {
//       id: "507f1f77bcf86cd799439030",
//       name: "Daniel Kim",
//       email: "d.kim@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Security Update Required",
//     text: "Mitul,\nPlease update your security credentials as per the new policy.\n\nRegards,\nDaniel",
//     date: new Date("2024-10-08T11:00:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["security", "important"],
//   },
//   {
//     id: "507f1f77bcf86cd799439031",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439032",
//       name: "Emily Clark",
//       email: "e.clark@example.com",
//     },
//     subject: "Project Milestone Review",
//     text: "Hi Emily,\nLet's schedule a meeting to review the project milestones.\n\nBest,\nMitul",
//     date: new Date("2024-10-07T15:45:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["project", "review"],
//   },
//   {
//     id: "507f1f77bcf86cd799439033",
//     sender: {
//       id: "507f1f77bcf86cd799439034",
//       name: "Tom Harris",
//       email: "t.harris@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Budget Forecast",
//     text: "Dear Mitul,\nAttached is the budget forecast for the next quarter.\n\nRegards,\nTom",
//     date: new Date("2024-10-06T10:30:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["finance", "forecast"],
//   },
//   {
//     id: "507f1f77bcf86cd799439035",
//     sender: {
//       id: "507f1f77bcf86cd799439036",
//       name: "Laura White",
//       email: "l.white@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Training Session Schedule",
//     text: "Hi Mitul,\nHere's the schedule for next week's training sessions.\n\nBest regards,\nLaura",
//     date: new Date("2024-10-05T13:20:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["training", "schedule"],
//   },
//   {
//     id: "507f1f77bcf86cd799439037",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439038",
//       name: "Kevin Park",
//       email: "k.park@example.com",
//     },
//     subject: "Feature Implementation Plan",
//     text: "Kevin,\nLet's discuss the implementation plan for the new feature.\n\nThanks,\nMitul",
//     date: new Date("2024-10-04T16:15:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["development", "planning"],
//   },
//   {
//     id: "507f1f77bcf86cd799439039",
//     sender: {
//       id: "507f1f77bcf86cd799439040",
//       name: "Nina Rodriguez",
//       email: "n.rodriguez@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Client Feedback Summary",
//     text: "Dear Mitul,\nHere's a summary of the client feedback from yesterday's meeting.\n\nBest,\nNina",
//     date: new Date("2024-10-03T09:00:00.000Z").toISOString(),
//      read: true,
//     archived: true,
//     trashed: false,
//     labels: ["client", "feedback"],
//   },
//   {
//     id: "507f1f77bcf86cd799439041",
//     sender: {
//       id: "507f1f77bcf86cd799439042",
//       name: "Peter Zhang",
//       email: "p.zhang@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "System Maintenance Notice",
//     text: "Important Notice:\n\nScheduled system maintenance this weekend. Please save all work beforehand.\n\nRegards,\nPeter",
//     date: new Date("2024-10-02T14:45:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["maintenance", "important"],
//   },
//   {
//     id: "507f1f77bcf86cd799439043",
//     sender: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439044",
//       name: "Anna Thompson",
//       email: "a.thompson@example.com",
//     },
//     subject: "Meeting Minutes",
//     text: "Hi Anna,\nAttached are the minutes from today's team meeting.\n\nBest,\nMitul",
//     date: new Date("2024-10-01T11:30:00.000Z").toISOString(),
//      read: true,
//     archived: false,
//     trashed: false,
//     labels: ["meeting", "minutes"],
//   },
//   {
//     id: "507f1f77bcf86cd799439045",
//     sender: {
//       id: "507f1f77bcf86cd799439046",
//       name: "Mark Davis",
//       email: "m.davis@example.com",
//     },
//     recipient: {
//       id: "507f1f77bcf86cd799439020",
//       name: "Mitul Mungase",
//       email: "mitul30m@icloud.com",
//     },
//     subject: "Performance Review Schedule",
//     text: "Hi Mitul,\nLet's schedule the performance review for next week.\n\nBest,\nMark",
//     date: new Date("2023-09-30T15:15:00.000Z").toISOString(),
//      read: false,
//     archived: false,
//     trashed: false,
//     labels: ["performance", "review"],
//   },
// ];

export const mails = [
  {
    id: "507f1f77bcf86cd799439001",
    sender: {
      id: "507f1f77bcf86cd799439011",
      name: "Exploreinn Support",
      email: "exploreinn@support.com",
    },
    recipient: {
      id: "507f1f77bcf86cd799439020",
      name: "Mitul Mungase",
      email: "mitul30m@icloud.com",
    },
    subject: "Welcome to Exploreinn!",
    text: "Hi Mitul, \nA warm welcome to Exploreinn! We're thrilled to have you on board. Exploreinn is your one-stop destination for booking the perfect hotel room for your next stay. Our platform offers a wide range of options to suit every taste and budget. \n\nTo get started, simply browse our collection of hotels, filter by location, price, and amenities, and book your dream room in just a few clicks. \n\nAs a valued member of our community, you can expect exclusive offers, discounts, and rewards. Our dedicated support team is always here to help you with any questions or concerns. \n\nThank you for choosing Exploreinn. We look forward to helping you create unforgettable memories. \n\nBest regards, \nExploreinn Support",
    date: new Date("2024-11-30T14:30:00.000Z").toISOString(),
    read: false,
    archived: false,
    trashed: false,
    labels: ["welcome", "onboarding", "exploreinn"],
  },
];

// export the type of the mail
export type Mail = (typeof mails)[number];

// inbox navigation
export const inboxNav = [
  {
    title: "Inbox",
    url: "#",
    icon: Inbox,
    isActive: true,
  },
  {
    title: "Archive",
    url: "#",
    icon: Archive,
    isActive: false,
  },
  {
    title: "Sent",
    url: "#",
    icon: Send,
    isActive: false,
  },
  {
    title: "Trash",
    url: "#",
    icon: Trash2,
    isActive: false,
  },
];
